# Generated by Django 3.1.4 on 2020-12-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20201212_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
